apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-dev-env
  name: ai-dev-env-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-dev-env-rolebinding
  namespace: ai-dev-env
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ai-dev-env
roleRef:
  kind: Role
  name: ai-dev-env-role
  apiGroup: rbac.authorization.k8s.io
